[profile.default]
solc = "0.8.25"
evm_version = "cancun"
src = "src"
test = "../PoC"
libs = ["lib"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
optimizer = true
optimizer_runs = 200
via_ir = true
ignored_error_codes = [3420, 2519, 3628, 2072, 5667, 2018]

[fmt]
single_line_statement_blocks = "multi"
multiline_func_header = "params_first"
sort_imports = true
contract_new_lines = true
bracket_spacing = true
int_types = "long"
quote_style = "double"
number_underscore = "thousands"
wrap_comments = true
